### ISSUE TITLE
Disabling ProxyToWorker option has no effect

### ISSUE THREAD

**Issue by sharifzadesina** [woodser/monero-ts#118]
Hello,

It seems `proxyToWorker: false` option has no effects. the library still opens a worker and even closing the wallet doesn't close the worker.
This causes for example Jest show us a warning message: "A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.".

**Comment by woodser** [comment]
I don't see that a worker is created with `proxyToWorker: false`. For example:

```js
let walletFull = await monerojs.createWalletFull({
  password: "abctesting123",
  networkType: "testnet",
  serverUri: "http://localhost:28081",
  proxyToWorker: false,
  rejectUnauthorized: false
});
```

Never executes `LibraryUtils.getWorker()`. Can you provide detailed steps to reproduce?

**Comment by sharifzadesina** [comment]
@woodser It is just Jest warning message.

**Comment by woodser** [comment]
If it helps, you can call:

```js
  // terminate monero-javascript worker
  (await monerojs.LibraryUtils.getWorker()).terminate();
```

But there may very well be something else at play.

**Comment by sharifzadesina** [comment]
It seems this is fixed on newer releases.
