### ISSUE TITLE
Errors swallowed in onOutputReceived and addListener

### ISSUE THREAD

**Issue by opx221** [woodser/monero-ts#171]
Hello

Lovely project, thanks guys
Can you please merge my commit that does not swallow errors/has more verbose logging
My issue is I am getting spontaneous errors "Failed to background poll undefined" and, secondly, when I get errors in onOutputReceived handler, they are swallowed
First one of these is specifically tedious for me to diagnose

Thank you

**Comment by woodser** [comment]
This is fixed in the last release. Thanks again for reporting.
