### ISSUE TITLE
getBalances doc is not correct

### ISSUE THREAD

**Issue by opx221** [woodser/monero-ts#177]
hello

`getBalances` doc says "Get the locked and unlocked balances in a single request.", but it returns (total) balance, not locked balance
I think it can be changed to just "Get the balance and unlocked balance in a single request."

**Comment by woodser** [comment]
Only the RPC wallet supports getBalances(), which returns an array with the total balance and unlocked balance.

I ran a quick test to ensure it's returning an array as expected.

**Comment by woodser** [comment]
Ah I just realized what you were saying, with the documentation being incorrect.

Fixed in https://github.com/woodser/monero-ts/pull/194/commits/e84126a644cdf0d6720bd6bb6bc1d382cdd48eb7.

Thanks.
