### ISSUE TITLE
Can't open wallet by keys

### ISSUE THREAD

**Issue by tothstevee** [woodser/monero-ts#179]
I have a wallet with all the keys view, spender, primary but when i try to open any wallet i got this error: 

MoneroRpcError: Failed to open wallet

`const walletRPC = await moneroTs.connectToWalletRpc(
        "http://127.0.0.1:18083"
    );

    await walletRPC.openWallet({
        path: "wallet_" + Date.now(),
        password: "monero",
        primaryAddress:
            "xxxx",
        privateViewKey:
            "xxxx",
        privateSpendKey:
            "xxx",
    });

    console.log(await walletRPC.getBalance());`

**Comment by woodser** [comment]
`openWallet` needs to be called with a path to a previously created wallet, so this fails because `"wallet_" + Date.now()` is always unique. First call `createWallet()`.

**Comment by tothstevee** [comment]
Thank! Now i understand how is it work. My other issue now is i'm getting back 0 balance but the account had some. Is that a daemon rpc issue?

**Comment by woodser** [comment]
The wallet needs to be synced from the wallet's restore height which requires a connection to daemon RPC.
