### ISSUE TITLE
MoneroWalletKeys.createSubaddress() not supported

### ISSUE THREAD

**Issue by AlexAnarcho** [woodser/monero-ts#183]
Heyo there! 
So we have a `MoneroWalletKeys` (view only wallet) on the client side and want to continously generate subaddresses with it. Intuitively we wanted to use `.createSubaddress()` but then got the error that it is not supported. 

Looking at the `src/main/ts/wallet/MoneroWallet.ts` it looks like this is not implemented, just for the `MoneroWalletFull`. We are wondering if the function of the `MoneroWalletFull` could not also be adopted for the `MoneroWalletKeys`. 

I guess a workable workaround is to use `MoneroWalletKeys.getAddress()` and then keep track of the subaddress index elsewhere.

Cheers!

**Comment by woodser** [comment]
MoneroWalletKeys provides only basic key access and doesn't maintain any wallet state.

View-only and offline wallets should use MoneroWalletFull. Here's [documentation](https://github.com/woodser/monero-ts/blob/master/docs/developer_guide/view_only_offline.md) for that.
