### ISSUE TITLE
Nice work, but I got into two issues that I can't work around

### ISSUE THREAD

**Issue by james-mou** [woodser/monero-ts#189]
1. on MoneroWalletFull class, the signature to create sub address looks like this:
  createSubaddress(accountIdx: number, label?: string): Promise<MoneroSubaddress>;

After digging around, I am convinced that accountIdx is NOT the index for the sub address I want to create, which means this code is relying on the wallet file to internally keep track of next available sub address index, which KILLS the possibility of working with a wallet just in memory without persisting it to disk, even if I fully take care of the persistence of primary address, private view key and last created sub address index in my code. The underlying monero protocol only needs primary address, private view key and a sub address index to create a sub address through a deterministic algorithm, but such elegance and simplicity is masked and lost by this library.

2. the following code is adapted from https://github.com/woodser/monero-ts/blob/master/docs/developer_guide/view_only_offline.md

import * as MoneroTs from 'monero-ts';

        this.readonlyWallet = await moneroTs.createWalletFull({
          path: DEFAULT_WALLET_NAME,
          networkType: moneroTs.MoneroNetworkType.MAINNET,
          primaryAddress: connectionInfo.mainAddress,
          privateViewKey: connectionInfo.privateViewKey,
          restoreHeight: requiredRestoreHeight,
          server: {
            uri: `http://127.0.0.1:${RPC_PORT}`,
            username: RPC_USERNAME,
            password: RPC_PASSWORD,
          },
        });

I get Error [TypeError]: Failed to parse URL, and adding "--no-experimental-fetch" on the node command does NOT fix it, while we are on this, I have another question, does this library have separate APIs for creating vs loading a wallet file? Because if I pre-create the actual view-only wallet via command line, loading it like the code below works, I thought the above code is equivalent to the code blow, is createWalletFull creating or loading a wallet??

   const WalletRPC = await MoneroTs.connectToWalletRpc(
      `http://127.0.0.1:${this.RPC_PORT}`,
      this.RPC_USERNAME,
      this.RPC_PASSWORD,
    );

    const readonlyWallet = await WalletRPC.openWallet(
      this.DEFAULT_WALLET_NAME,
      this.WALLET_PASSWORD,
    );

**Comment by woodser** [comment]
If you want to derive arbitrary subaddresses instead of the wallet auto-tracking "new" subaddresses (based on wallet2), you should use the keys-only wallet. For example:

```
let wallet = await moneroTs.createWalletKeys({...}); // fully in-memory
let mySubaddress = await wallet.getAddress(myAccountIdx, mySubaddressIdx);
```

> I get Error [TypeError]: Failed to parse URL, and adding "--no-experimental-fetch" on the node command does NOT fix it

Please provide more details about your environment or better, open a new issue to track this.

> is createWalletFull creating or loading a wallet

`createWalletFull` creates a new wallet, which is fully compatible to load with the library, monero-wallet-rpc, or the CLI.

Alternatively, `openWalletFull` opens a wallet, which was previously created from the library, monero-wallet-rpc, or CLI.

`moneroTs.connectToWalletRpc` merely connects to a monero-wallet-rpc server which must have created or loaded a wallet, again fully compatible.

Hope this helps.

**Comment by james-mou** [comment]
Thanks for the prompt reply, createWalletKeys sounds promising, I will try it out and report back ASAP.

**Comment by james-mou** [comment]
createWalletKeys gives the same error:

[0] Error [TypeError]: Failed to parse URL from /code/src/monero-test/node_modules/monero-ts/dist/dist/monero_wallet_keys.wasm
[0]     at LibraryUtils.deserializeError (/code/src/monero-test/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:253:106)
[0]     at LibraryUtils.invokeWorker (/code/src/monero-test/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:242:26)
[0]     at async MoneroWalletKeysProxy.createWallet (/code/src/monero-test/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:381:5)
[0]     at async MoneroWalletKeys.createWallet (/code/src/monero-test/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:63:25)
[0]     at async MoneroPaymentEngine.connectRPC (file:///code/src/monero-test/dist/order/moneroService.js:47:35)
[0] Worker error: TypeError: Failed to parse URL from /code/src/monero-test/node_modules/monero-ts/dist/dist/monero_wallet_keys.wasm

my environment:

❯ node --version
v20.11.1

OS: linux, kernel 6.1.53

this is the code, which URL is it talking about? the rpc server? please note, github removes the backquotes around server's uri, which does exist in my running code

      this.readonlyWallet = await MoneroTs.createWalletKeys({
        path: DEFAULT_WALLET_NAME,
        networkType: MoneroTs.MoneroNetworkType.MAINNET,
        primaryAddress: connectionInfo.mainAddress,
        privateViewKey: connectionInfo.privateViewKey,

        server: {
          uri: `http://127.0.0.1:${RPC_PORT}`,
          username: RPC_USERNAME,
          password: RPC_PASSWORD,
        },
      });

**Comment by james-mou** [comment]
one more question, I kind of feel  monero-wallet-rpc is probably the least solid part of the whole monero project, and monerod does have a low level rpc interface, if all I want to do is to generate sub addresses and monitor incoming transfers, is it possible to completely cut out  monero-wallet-rpc and go monero-ts ==> monerod?

**Comment by woodser** [comment]
> which URL is it talking about? the rpc server?

The URL refers to the loading the .wasm files, so you can run a wallet locally which connects directly to monerod, instead of using the monero-wallet-rpc server at all.

> is it possible to completely cut out monero-wallet-rpc and go monero-ts ==> monerod?

Yes, we just need to load those .wasm files for local wallet functionality.

**Comment by james-mou** [comment]
export NODE_OPTIONS=--openssl-legacy-provider worked, you can close this issue now, thanks.
