### ISSUE TITLE
Method not found | rpcMethod: 'open_wallet'

### ISSUE THREAD

**Issue by NaNtheDev** [woodser/monero-ts#199]
So I need to code a payment system that supports monero and I'm having a little problem loading the wallet already generated on the monero GUI. As soon as I try to run the code to use `app.wallet` I get this error:
```
MoneroRpcError: Method not found
 at MoneroRpcConnection.validateRpcResponse (C:\Us\user\Desktop\paysystem\backend\node_modules\monero-ts\dist\s\rcaints\common\MoneroRpcConnection.js:415:11)
 at MoneroRpcConnection.sendJsonRequest (C:\Users\user\Desktop\paysystem\backend\node_modules\monero-ts\dist\src\maints\common\MoneroRpcConnection.js:273:27)
 at async MoneroWalletRpc.openWallet (C:\Users\user\Desktop\paysystem\backend\node_modules\monero-ts\dist\src\maints\wallet\MoneroWalletRpc.js:161:5)
 at async file:///C:/Users/user/Desktop/paysystem/backend/index.js:17:14 {
 code: -32601,
 rpcMethod: 'open_wallet',
 rpcParams: {
 filename: './wallet/paysystem',
 password: 't4GzTpZx3mU@vqWy}SPcEr'
 }
}

Node.js v18.16.0
```
*Hackers who have the password, you won't get far it's a stagenet wallet lol*
Here is my code: 
```js
const walletRpc = await moneroTs.connectToWalletRpc(`http://${config.wallet.host}:${config.wallet.port}`);
app.wallet = await walletRpc.openWallet({
    path: './wallet/PrefixOfPrivacy',
    password: config.wallet.password,
    networkType: moneroTs.MoneroNetworkType.STAGENET,
    seed: config.wallet.seed,
    restoreHeight: config.wallet.restore_height,
});
```
**IT IS IMPORTANT TO NOTE THAT CONFIG.WALLET IS GOOD! I have checked everything.**
config.json: 
```json
"wallet": {
    "host": "node3.monerodevs.org",
    "port": 38089
}
```
I use a public node in stagenet
**Thank you to anyone who can help me with this problem, which is a major obstacle to my project.**

**Comment by NaNtheDev** [comment]
![image](https://github.com/woodser/monero-ts/assets/52248252/077c1a22-3e92-4921-a43e-7de0a2029bf4)
And this is my wallet folder

**Comment by woodser** [comment]
I believe the path needs to be a standard file name, instead of a path to the wallet.

**Comment by NaNtheDev** [comment]
> I believe the path needs to be a standard file name, instead of a path to the wallet.

What do you mean by that?

**Comment by woodser** [comment]
For example, just "PrefixOfPrivacy", instead of "./wallet/PrefixOfPrivacy", so there's not a path in the filename.

**Comment by NaNtheDev** [comment]
Thanks for your answer, but it doesn't solve the problem :/.
Here is my index.js
![image](https://github.com/woodser/monero-ts/assets/52248252/b0f7ceb9-332b-4e86-b7c6-3d4bca97f041)
And this is my file structure
![image](https://github.com/woodser/monero-ts/assets/52248252/97b7017d-c8d6-48fa-985d-a9a3fe2eeb91)
![image](https://github.com/woodser/monero-ts/assets/52248252/aaf63150-df4c-4ce9-9b2d-6d16b2ad63c2)
*I have the same error*

**Comment by woodser** [comment]
Are you connecting to an instance of monero-wallet-rpc server and not monerod?

You'll need to connect to monero-wallet-rpc server and then connect that to monerod, instead of connecting directly to monerod.

You can use the full wallet to connect directly to monerod.

**Comment by NaNtheDev** [comment]
In fact, I'm connecting to a monero node that must run with monerod, so if I've understood correctly, I must connect to moner-wallet-rpc in localhost, which connects to the monero stagenet node.

**Comment by woodser** [comment]
Yep, or use the local full wallet to connect to monerod directly.

**Comment by NaNtheDev** [comment]
Thanks for your help! I'm running the monero-wallet-rpc with docker and it connects to my test node! Solved one thousand thanks!
