### ISSUE TITLE
MoneroError: Invalid mnemonic

### ISSUE THREAD

**Issue by znwhite** [woodser/monero-ts#210]
I am trying to generate a wallet that I can share with an individual user(s) as a place to send Monero.

I want to generate the wallet on the server, save the private/view keys for myself, and share the public address with the user.

But when trying to create a wallet, I am getting an error: `MoneroError: Invalid mnemonic`

<img width="1087" alt="error-log" src="https://github.com/woodser/monero-ts/assets/66323186/d2046766-53cc-4133-8aa8-08ac75503ad5">

Here is the code:

```
const seed = generateSeed();

let wallet = await moneroTs.createWalletKeys({
    password: "abc123",
    networkType: moneroTs.MoneroNetworkType.MAINNET,
    seed
  });
```

`generateSeed()` is a function I created that produces a string of 25 words from this list of words: https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h#L52

For example, here is a  string that failed and gave me the above error:
`swim surf library write ski read peach apple code anchor type quiet penguin sun design bake draw umbrella create exercise mirror monkey zebra egg octopus`

Can someone tell me what I am doing wrong? Thank you.

===========================

**UPDATE:** it looks like if I remove the `seed` field it works? So I don't need to pass in a `seed` to generate a valid wallet after all?

For example this seems to be working:

```
 let wallet = await moneroTs.createWalletKeys({
    language: "English",
    password: "abc123",
    networkType: moneroTs.MoneroNetworkType.MAINNET,
  });
  const privateKey = await wallet.getPrivateViewKey();
  const publicAddress = await wallet.getPrimaryAddress();
  const walletSeed = await wallet.getSeed();

  console.log("PUBLIC ADDRESS", publicAddress);
  console.log("PRIVATE VIEW KEY", privateKey);
  console.log("WALLET SEED", walletSeed);
```

**Comment by woodser** [comment]
Yeah you can omit the seed and it will generate a new one.

Or you can provide a seed to restore from, using the syntax `seed: ...`. Your syntax above is incorrect, because it only provides `seed`:

```
let wallet = await moneroTs.createWalletKeys({
    password: "abc123",
    networkType: moneroTs.MoneroNetworkType.MAINNET,
    seed <--- should be "seed: ..."
  });
```

**Comment by znwhite** [comment]
Thanks @woodser , yes after closer reading of the docs I realize that the create wallet methods do different things depending on what config you pass them.

If you pass a seed it knows you're trying to recover a wallet, if you pass only a view key it knows to just fetch the view-only version of the wallet, if you pass only networkType/language it knows you are trying to generate a new wallet, etc. Didn't realize this at first. 

Closing now! Thanks again.

**Comment by znwhite** [comment]
@woodser can you please delete this issue? github wont let me. Thank you 🙏
