### ISSUE TITLE
Error importing monero-ts since updating Axios

### ISSUE THREAD

**Issue by woodser** [woodser/monero-ts#235]
Since the Axios update in v0.10.1, I'm hitting an error using monero-ts in [haveno-ts](https://github.com/haveno-dex/haveno-ts/blob/4345976f20c4625fe467ad445f15174bd557cf80/src/HavenoClient.test.ts#L53):

```
 FAIL  src/HavenoClient.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/woodser/git/haveno-ts/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import axios from './lib/axios.js';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      51 | import assert from "assert";
      52 | import console from "console"; // import console because jest swallows messages in real time
    > 53 | import moneroTs from "monero-ts";
         | ^
      54 | import * as os from 'os';
      55 |
      56 | // ------------------------------ TEST CONFIG ---------------------------------

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/monero-ts/src/main/ts/common/HttpClient.ts:7:1)
      at Object.<anonymous> (node_modules/monero-ts/index.ts:11:1)
      at Object.<anonymous> (src/HavenoClient.test.ts:53:1)
```

**Comment by woodser** [comment]
@mainnet-pat Hoping you can help fix this? It doesn't like the `import axios` statement for some reason.

**Comment by woodser** [comment]
Relevant stackoverflow: https://stackoverflow.com/questions/73958968/cannot-use-import-statement-outside-a-module-with-axios

**Comment by mainnet-pat** [comment]
How can I reproduce this locally?

**Comment by mainnet-pat** [comment]
My other projects never showed these erorrs

**Comment by woodser** [comment]
> How can I reproduce this locally?

By running any of the tests in the haveno-ts project: https://github.com/haveno-dex/haveno-ts?tab=readme-ov-file#run-tests

**Comment by woodser** [comment]
> My other projects never showed these erorrs

Yeah I didn't see it in any of the sample apps. It was my mistake to not test it in haveno-ts prior to release.

**Comment by woodser** [comment]
According to the stackoverflow, the issue might resolve by updating to the latest version of jest, but that introduces its own build issue (`ReferenceError: proto is not defined`).

**Comment by mainnet-pat** [comment]
Cant look too deep into this. Packing the bags for a weekend trip.

It seemed to help me to install the following (latest versions):

`npm i --save-dev jest @types/jest ts-jest ts-jest-resolver`

remove your config from package.json and add a jest.config.cjs from my other project:

```
module.exports = {
  rootDir: "./",
  preset: "ts-jest/presets/default-esm",
  resolver: "ts-jest-resolver",
  collectCoverage: true,
  collectCoverageFrom: [
    "**/*.{js,jsx,ts}",
    "!**/node_modules/**",
  ],
  coveragePathIgnorePatterns: [
    ".*/src/.*\\.d\\.ts",
    ".*/src/.*\\.test\\.{ts,js}",
    ".*/src/.*\\.test\\.headless\\.js",
  ],
  roots: [
    "<rootDir>/src",
  ],
  testMatch: [
    "**/__tests__/**/*.+(ts|tsx|js)",
    "**/?(*.)+(spec|test).+(ts|tsx|js)",
  ],
  transform: {
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        useESM: true,
      },
    ],
  },
  testEnvironment: "node",
  verbose: true,
  maxConcurrency: 1,
  testTimeout: 180000,
  testPathIgnorePatterns: [
    "/node_modules/",
    "/dist/",
  ],
  globals: {
    window: {}
  },
};
```

**Comment by mainnet-pat** [comment]
Looks like linter stuff, so should be fixable

**Comment by mainnet-pat** [comment]
for example like this:

```
class PeerContext {
  havenod!: HavenoClient;
  wallet!: moneroTs.MoneroWallet;
  trade!: TradeInfo;
....
```

**Comment by woodser** [comment]
Fixing the lint errors gets closer, but now getting: `XMLHttpRequest is not defined`.

**Comment by mainnet-pat** [comment]
it is not defined for node

**Comment by woodser** [comment]
Got further by changing `testEnvironment: "node"` to `testEnvironment: "jsdom"`, but now getting cors errors because requests originate from "http://localhost" instead of "http://localhost:8080".

**Comment by woodser** [comment]
Adding "testURL": "http://localhost:8080" changes the error to: `401 Unauthorized: <html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>`

As of now I'm still not able to use the new monero-ts update in the haveno-ts library.

**Comment by woodser** [comment]
> Adding "testURL": "http://localhost:8080/" changes the error to: 401 Unauthorized: <html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>

I'm wondering if it's not succeeding on the digest authentication challenge.

**Comment by mainnet-pat** [comment]
This seems like the response from the daemon, why would jest render this?

**Comment by mainnet-pat** [comment]
I can not compile the protobuf stuff atm. so can not test exactly your code

**Comment by mainnet-pat** [comment]
Built haveno and protobuf but fail with `TypeError: Jest: a transform must export a `process` function.`

I run out of time, will be back on Monday

**Comment by woodser** [comment]
Here is the error in the CI tests if it helps: https://github.com/haveno-dex/haveno-ts/actions/runs/10564898796/job/29268294819

**Comment by mainnet-pat** [comment]
I've spent 3 more hours on this, I still can not set up the haveno envronment locally, it is simply too complex. If monero-ts returns you actual 401 response with some body, this means that axios http client works. I think this is beyond the scope of my involvement here.

I have tried monero-ts in other projects, and new http client adaptor based on axios works for me there.

**Comment by woodser** [comment]
I can offer a bounty of 2 additional XMR to fix using the library in haveno-ts. As it is, I'm stuck. I'd be happy to DM to help set up the haveno-ts environment so we don't lose time there.

**Comment by mainnet-pat** [comment]
Okay, I take this bounty offer and will take another look at haveno-ts.

My main problem is that your docker setup is using host networking which does not work in my macOS environment. Firstly I want to migrate the docker compose setup to use docker internal networking, then it will be better portable and testable

**Comment by woodser** [comment]
> your docker setup is using host networking

Ah! I was just playing with this yesterday, and realized that on macOS, it will *not work* if you include `--network host` in the command to start envoy.

So this needs removed and it should work as is.

**Comment by mainnet-pat** [comment]
this would not be enough, proper ports shall be exposed and services linked by name like `--daemon-address=node1:18081` instead of by ip like `--daemon-address=127.0.0.1:18081`

**Comment by woodser** [comment]
I'd highly recommend getting the project running as is before updating things (which would be great). Again, happy to help get that first step working over DM or here or whatever.

**Comment by mainnet-pat** [comment]
the best I can do to make it run as is is to test on some linux vps (I assume you run linux, at least github actions are linux based)

**Comment by woodser** [comment]
I'm running macOS, and all tests pass for me on that environment.

**Comment by woodser** [comment]
It also requires an old version of Docker.

**Comment by mainnet-pat** [comment]
well, idk about downgrading my docker, but if you *mean* it, I will do

**Comment by woodser** [comment]
Yes it will definitely not work with the latest version of docker. I lost the better part of yesterday wrestling with this. Downgrading back to [Docker 4.26.1](https://docs.docker.com/desktop/release-notes/#4261) worked like a charm.
